#! /bin/bash

#Kali-Linux

#VARIABLES
             red='\033[1;31m'                                        green='\033[1;32m'
             yellow='\033[1;33m'                                     blue='\033[1;34m'                                       magenta='\033[1;35m'                                    cyan='\033[1;36m'
             reset='\033[0m'

printf $cyan
echo "
░█░█░█▀█░█░░░▀█▀░░░░░█░░░▀█▀░█▀█░█░█░█░█
░█▀▄░█▀█░█░░░░█░░▄▄▄░█░░░░█░░█░█░█░█░▄▀▄
░▀░▀░▀░▀░▀▀▀░▀▀▀░░░░░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ "
printf $reset
sleep 1.0
clear
cd 

cd $HOME/MR.-Linux-master
apt update -y
apt upgrade -y 
printf $cyan
echo "INSTALANDO KALI-LINUX"
sleep 1.5
printf $reset
pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh
cd $HOME/MR.-Linux-master/kali-fs/etc
ls
rm bash.bashrc
cd
cp $HOME/MR.-Linux-master/bash.bashrc $HOME/KALI-LABDYLANYT/kali-fs/etc
cd $HOME/MR.-Linux-master/
clear
./start-kali.sh
