#!/bin/bash
pkg update && pkg upgrade
clear
pkg install root-repo -y
pkg install figlet -y
clear
setterm -foreground green
echo " Pulsa ENTER para confirmar la instalación "
read ENTER
pkg install proot -y
pkg install vim -y
pkg install wget -y
su
pkg install tsu -y
clear
wget https://dylan14567.github.io/Laboratorio-SUPERDYLANYT/start-root.sh
clear
chmod 777 start-root.sh
rm servidordedatos;ls





